const fs = require('fs');
const path = require('path');

// Read the .env file from the project root
const envPath = path.resolve(__dirname, '../.env');
let envConfig = {};

if (fs.existsSync(envPath)) {
  const envFile = fs.readFileSync(envPath, 'utf8');
  envFile.split(/\r?\n/).forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;
    const parts = line.split('=');
    if (parts.length >= 2) {
      const key = parts[0].trim();
      let value = parts.slice(1).join('=').trim();
      // Remove surrounding quotes if any
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.substring(1, value.length - 1);
      }
      envConfig[key] = value;
    }
  });
} else {
  console.warn(`Warning: .env file not found at ${envPath}. Using empty default values.`);
}

// Generate the environments directory if it doesn't exist
const environmentsDir = path.resolve(__dirname, '../src/environments');
if (!fs.existsSync(environmentsDir)) {
  fs.mkdirSync(environmentsDir, { recursive: true });
}

const getVar = (key, defaultValue = '') => {
  return envConfig[key] || process.env[key] || defaultValue;
};

const writeEnvFile = (isProd) => {
  const targetPath = path.join(environmentsDir, isProd ? 'environment.prod.ts' : 'environment.ts');
  const content = `// This file was autogenerated by tools/set-env.js
export const environment = {
  production: ${isProd},
  apiUrl: '${getVar('API_URL', 'https://u-ride-backend.onrender.com/api')}',
  institutionEmailDomain: '${getVar('INSTITUTION_EMAIL_DOMAIN', 'uta.edu.ec')}',
  firebaseConfig: {
    apiKey: "${getVar('FIREBASE_API_KEY')}",
    authDomain: "${getVar('FIREBASE_AUTH_DOMAIN')}",
    databaseURL: "${getVar('FIREBASE_DATABASE_URL')}",
    projectId: "${getVar('FIREBASE_PROJECT_ID')}",
    storageBucket: "${getVar('FIREBASE_STORAGE_BUCKET')}",
    messagingSenderId: "${getVar('FIREBASE_MESSAGING_SENDER_ID')}",
    appId: "${getVar('FIREBASE_APP_ID')}"
  }
};
`;
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Generated ${isProd ? 'production' : 'development'} environment file at: ${targetPath}`);
};

writeEnvFile(false); // environment.ts
writeEnvFile(true);  // environment.prod.ts
